mqtt:
  enabled: false

detectors:
  ov:
    type: openvino
    device: CPU
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

  input_dtype: int
  model_type: ssd
cameras:     # No cameras defined, UI wizard should be used
  street_-_sofia:
    enabled: true
    friendly_name: Street - Sofia
    ffmpeg:
      inputs:
        - path: 
            rtsp://selyandur:Selyandur1@192.168.1.251:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
          roles:
            - record
        - path: 
            rtsp://selyandur:Selyandur1@192.168.1.251:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_2
          roles:
            - detect
    detect:
      width: 352
      height: 288
    live:
      streams:
        Stream 1: street_-_sofia_1
        Stream 2: street_-_sofia_2
    motion:
      mask:
        motion_mask_1:
          friendly_name: Motion Mask 1
          enabled: true
          coordinates: 0,0,1,0,0.995,0.994,0.625,0.997,0.622,0.249,0,0.258
        motion_mask_2:
          friendly_name: Motion Mask 2
          enabled: true
          coordinates: 0,0.257,0.397,0.253,0,0.669
  street_-_plovdiv:
    enabled: true
    friendly_name: Street - Plovdiv
    ffmpeg:
      inputs:
        - path: 
            rtsp://192.168.1.246:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp?real_stream
          roles:
            - record
        - path: 
            rtsp://192.168.1.246:554/user=admin_password=tlJwpbo6_channel=1_stream=1.sdp?real_stream
          roles:
            - detect
    detect:
      width: 704
      height: 576
    live:
      streams:
        Stream 1: street_-_plovdiv_1
        Stream 2: street_-_plovdiv_2
    motion:
      mask:
        motion_mask_1:
          friendly_name: Motion Mask 1
          enabled: true
          coordinates: 0.001,0.003,1,0,1,0.33,0,0.344
        motion_mask_2:
          friendly_name: Motion Mask 2
          enabled: true
          coordinates: 0.002,0.345,0.42,0.337,0.318,1,0,1
    timestamp_style:
      position: tr
  house_martin:
    enabled: false
    friendly_name: House Martin
    ffmpeg:
      inputs:
        - path: 
            rtsp://192.168.1.249:554/user=admin_password=tlJwpbo6_channel=0_stream=0.sdp?real_stream
          roles:
            - record
        - path: 
            rtsp://192.168.1.249:554/user=admin_password=tlJwpbo6_channel=0_stream=1.sdp?real_stream
          roles:
            - detect
    detect:
      width: 640
      height: 360
    live:
      streams:
        Stream 1: house_martin_1
        Stream 2: house_martin_2
version: 0.18-0
ffmpeg:
  hwaccel_args: preset-vaapi
go2rtc:
  streams:
    street_-_sofia_1:
      - rtsp://selyandur:Selyandur1@192.168.1.251:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    street_-_sofia_2:
      - rtsp://selyandur:Selyandur1@192.168.1.251:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_2
    street_-_plovdiv_1:
      - rtsp://192.168.1.246:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp?real_stream
    street_-_plovdiv_2:
      - rtsp://192.168.1.246:554/user=admin_password=tlJwpbo6_channel=1_stream=1.sdp?real_stream
    house_martin_1:
      - rtsp://192.168.1.249:554/user=admin_password=tlJwpbo6_channel=0_stream=0.sdp?real_stream
    house_martin_2:
      - rtsp://192.168.1.249:554/user=admin_password=tlJwpbo6_channel=0_stream=1.sdp?real_stream
detect:
  enabled: true
record:
  enabled: true
  motion:
    days: 3
semantic_search:
  enabled: false
notifications:
  email: mbelianov@gmail.com
  enabled: true
camera_groups: {}
auth:
  roles: {}
environment_vars: {}
telemetry:
  network_interfaces:
    - eth0
  stats: {}
